# Use postgres/example user/password credentials
version: "3.9"

services:
  postgres_golang:
    image: postgres:latest
    restart: always
    container_name: postgres_go
    environment:
      POSTGRES_DB: db_go
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
